id: P003238
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-17 10:49:30.352443
source_metadata:
  id: bdr:W1KG21291
  title: སྐྱབས་འགྲོ་བྲན་གཡོག་གི་འདུ་ཤེས་ཡིན་ནམ།
  author: ''
  volumes:
    c33edb432a4542478f4720be5efda757:
      image_group_id: I1KG21571
      title: ''
      volume_number: 1
      total_pages: 184
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
